### ISSUE TITLE
Release 1.1 still has previous problems

### ISSUE THREAD

**Issue by hwalker6742** [AA6KL/NanoVNA-H4#2]
Ken,
   Revision 1.1 fixed the touchscreen sensitivity and DFU file generation issues but the  following problem still remains after the upgrade was complete:

   The center frequency problem reported in hugen79/NanoVNA-H#25 is still present in your upgrade.

   I also was puzzled that your firmware causes  the NanoVNA-H4 to appear on a different serial port (COM4) then it did before (COM9).  My other NanoVNA's with hugen's releases all appear on COM9.

   Pmax (Massimo) sent me a notification that the center frequency issue has been debugged and will be fixed with hugen's next firmware release.  You probably should consult with him regarding the fix.

  I will close out the first issue.
Herb

**Comment by Pmax65** [comment]
Hi Herb,
I suspect that Hugen still haven't included Ken's mod to fix the center frequency issue, for this reason you can't get it fixed now.
Unluckily, I never used this kind of multi-software-engineer programming before, and I've no idea about how to apply my mod to Hugen's code.
Anyways Ken's mod does more or less exactly what my mod does and for that it should work indeed.

Have a great day.

Massimo IK1IZA

**Comment by hwalker6742** [comment]
Massimo,
  Ken just released v1.2 and it resolves the center frequency issue.  Thanks to all.  Looking forward to see what future enhancements are planned.  Closing issue #2 out.

- Herb
